//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Framework_Ass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_data
    {
        public int student_id { get; set; }
        public string student_Name { get; set; }
        public string student_FatherName { get; set; }
        public Nullable<int> student_age { get; set; }
        public string Email { get; set; }
    }
}
